import '@vue/runtime-core';

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    ElAlert: typeof import('element-plus/es')['ElAlert'];
    VanTabbar: typeof import('vant/es')['Tabbar'];
    VanTabbarItem: typeof import('vant/es')['TabbarItem'];
    VanSwipe: typeof import('vant/es')['Swipe'];
    VanSwipeItem: typeof import('vant/es')['SwipeItem'];
    VanNavBar: typeof import('vant/es')['NavBar'];
    VanTab: typeof import('vant/es')['Tab'];
    VanTabs: typeof import('vant/es')['Tabs'];
    VanToast: typeof import('vant/es')['Toast'];
    VanCell: typeof import('vant/es')['Cell'];
    VanCellGroup: typeof import('vant/es')['CellGroup'];
    VanImage: typeof import('vant/es')['Image'];
    VanCol: typeof import('vant/es')['Col'];
    VanRow: typeof import('vant/es')['Row'];
    VanGrid: typeof import('vant/es')['Grid'];
    VanGridItem: typeof import('vant/es')['GridItem'];
    VanIcon: typeof import('vant/es')['Icon'];
    VanSidebar: typeof import('vant/es')['Sidebar'];
    VanSidebarItem: typeof import('vant/es')['SidebarItem'];
    VanCard: typeof import('vant/es')['Card'];
    VanTag: typeof import('vant/es')['Tag'];
    VanList: typeof import('vant/es')['List'];
    VanSticky: typeof import('vant/es')['Sticky'];
    VanButton: typeof import('vant/es')['Button'];
    VanTreeSelect: typeof import('vant/es')['TreeSelect'];
    VanPicker: typeof import('vant/es')['Picker'];
    VanForm: typeof import('vant/es')['Form'];
    VanField: typeof import('vant/es')['Field'];
    VanPopup: typeof import('vant/es')['Popup'];
    VanTabbarItem: typeof import('vant/es')['TabbarItem'];
    VanSwipe: typeof import('vant/es')['Swipe'];
    VanSwipeItem: typeof import('vant/es')['SwipeItem'];
    VanNavBar: typeof import('vant/es')['NavBar'];
    VanTab: typeof import('vant/es')['Tab'];
    VanTabs: typeof import('vant/es')['Tabs'];
    VanToast: typeof import('vant/es')['Toast'];
    VanCell: typeof import('vant/es')['Cell'];
    VanCellGroup: typeof import('vant/es')['CellGroup'];
    VanImage: typeof import('vant/es')['Image'];
    VanCol: typeof import('vant/es')['Col'];
    VanRow: typeof import('vant/es')['Row'];
    VanGrid: typeof import('vant/es')['Grid'];
    VanGridItem: typeof import('vant/es')['GridItem'];
    VanIcon: typeof import('vant/es')['Icon'];
    VanSidebar: typeof import('vant/es')['Sidebar'];
    VanSidebarItem: typeof import('vant/es')['SidebarItem'];
    VanCard: typeof import('vant/es')['Card'];
    VanTag: typeof import('vant/es')['Tag'];
    VanList: typeof import('vant/es')['List'];
    VanSticky: typeof import('vant/es')['Sticky'];
    VanButton: typeof import('vant/es')['Button'];
    VanTreeSelect: typeof import('vant/es')['TreeSelect'];
    VanPicker: typeof import('vant/es')['Picker'];
    VanForm: typeof import('vant/es')['Form'];
    VanField: typeof import('vant/es')['Field'];
    VanPopup: typeof import('vant/es')['Popup'];
  }
}
